 <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit contact';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'contact',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('surname'));
 echo $this->formRow($form->get('mail'));
 echo $this->formRow($form->get('social'));
 echo $this->formRow($form->get('residence'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();