
    <!-- BEGIN Timeline Embed -->
    <div id="timeline-embed"></div>
    <script type="text/javascript">
      var timeline_config = {
       width: "100%",
       height: "100%",
       source: 'data.json',
       font:	'SansitaOne-Kameron'
      }
    </script>
    <!-- build:js http://cdn.knightlab.com/libs/timeline/latest/js/storyjs-embed.js -->
    <script type="application/javascript">
        var embed_path = "/build/"
    </script>
    <script type="text/javascript" src="./public/js/storyjs-embed.js"></script>
    <!-- endbuild -->
    <!-- END Timeline Embed-->
    <!-- Analytics-->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-537357-19']);
      _gaq.push(['_trackPageview']);
      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
