
 <div class="jumbotron">
    <h1><?php echo sprintf($this->translate('%sMy Albums%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Music Sample List')) ?></p>
    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('album', array('action'=>'add'));?>" target="_blank"><?php echo $this->translate('Add new album') ?> &raquo;</a></p>
</div>
<div class="col_md_4">
	<table class="table">
		<tr>
     		<th>Title</th>
     		<th>Artist</th>
     		<th>&nbsp;</th>
 		</tr>
		<?php foreach ($albums as $album) : ?>
 		<tr>
     		<td><?php echo $this->escapeHtml($album->title);?></td>
     		<td><?php echo $this->escapeHtml($album->artist);?></td>
     		<td>
         		<a href="<?php echo $this->url('album',
             		array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
         		<a href="<?php echo $this->url('album',
             		array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     		</td>
 		</tr>
 		<?php endforeach; ?>
 	</table>
</div>