<?php 
//use Application;
use Zend\EventManager\ResponseCollection;
use Zend\ModuleManager\Listener\AutoloaderListener;
use Zend\ModuleManager\ModuleManager as MM;
use Zend\Mvc\Service\ModuleManagerFactory;
echo $this->doctype(); 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Antonio Blasco Cerrada '. $this->translate('SysAdmyn & PHP Developer'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/abc.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')                       
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">              
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/abc-ico.png') ?>" alt="ABC Developer"/><?php echo $this->translate('Antonio Blasco Cerrada') ?></a>               
                </div>
                <div class="collapse navbar-collapse">              	
                    <ul class="nav navbar-nav">
                        <li class="btn">
                        	<a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a>
                        </li>                                                                              	
                   	</ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="container">
            <div class="row">
               <div class="col-md-4">
                     <div class="panel-body" align="center">
                        <p>Developed under<a class="btn" align='center' target="_blank" href="https://php.net">PHP</a></p>
                     </div>
               </div>
               <div class="col-md-4">
                     <div class="panel-body" align="center">
                        <p>Powered by<a class="btn" align='center' target="_blank" href="https://framework.zend,com">Zend Framework 2</a></p>
                     </div>
               </div>
               <div class="col-md-4">
                     <div class="panel-body" align="center">
                        <p>And styled by<a class="btn" align='center' target="_blank" href="https://getbootstrap.com">Bootstrap 3</a></p></p>
                     </div>
               </div>
            </div>                
        </div>
     <div class="row">  
        <p align='center'> &copy; 2014 - <?php echo date('Y') ?> by 814ck.c0d3 Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
     </div>     
 </nav>
        </div> <!-- /container -->
 
    </body>
</html>							