<ul class="nav navbar-nav navbar-right">
<li class="btn">
<button class="btn" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
	<span class="glyphicon glyphicon-list" aria-hidden="true"></span>
		Site Map
	<span class="caret"></span>
</button>
<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
	<li role="presentation"><a><?php echo ($this->navigation('navigation')->menu());?></a></li>
</ul>
</li>
</ul>

