<nav class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <img src="<?php echo $this->basePath('img/apps-logo.png') ?>" alt="ABC Developer Knowledge"/>&nbsp;
                </div>
            </div>
        </nav>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('SysAdmin & PHP developer') ?></h3>
            </div>
            <div class="panel-body" align="center">
			    <p>
			    	<img src="<?php echo $this->basePath('img/foto.jpg') ?>" alt="ABC"/>&nbsp;
			    </p>
			    <p>
		        	<a class="btn" target="_blank" href="https://www.linkedin.com/profile/view?id=378862513">
	        			<img src="<?php echo $this->basePath('img/linkedin.png') ?>" alt="LinkedIn"/>&nbsp;
        			</a>
        			<a class="btn" target="_blank" href="https://github.com/814ckc0d3/">
            			<img src="<?php echo $this->basePath('img/github.png') ?>" alt="github"/>&nbsp;
        			</a>
        			<a class="btn" target="_blank" href="https://twitter.com/814ck_c0d3">
            			<img src="<?php echo $this->basePath('img/twitter.png') ?>" alt="Twitter"/>&nbsp;
        			</a>
        			<a class="btn" target="_blank" href="">
            			<img src="<?php echo $this->basePath('img/google.png') ?>"/>&nbsp;
        			</a>
    			</p>
             </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Oracle Technologies') ?></h3>
            </div>
            <div class="panel-body" align="left">
            <img src="<?php echo $this->basePath('img/oracle-uni.png') ?>" alt="Oracle University"/>&nbsp;
            </div>
            <div class="panel-body" align="right">
                <p><?php echo $this->translate('Oracle ID: OC1349879‎') ?></p>
                <p><?php echo $this->translate('OCA Oracle Weblogic Server 11g') ?></p>
                <p><?php echo $this->translate('OCP Oracle Database 11g') ?></p>
                <p><?php echo $this->translate('MySQL Server 5.6') ?></p>
            </ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Zend Technologies') ?></h3>
            </div>

            <div class="panel-body" align="left">
            	<img src="<?php echo $this->basePath('img/zend-logo.png') ?>" alt="Twitter"/>&nbsp;
            </div>
            <div class="panel-body" align="right">
                <p><?php echo $this->translate('Zend ID: ZEND026644') ?></p>
                <p><?php echo $this->translate('Zend PHP 5.3 Enginner') ?></p>
                <p><?php echo $this->translate('Zend Framework 2') ?></p>
            </div>
        </div>
    </div>
</div>